name: Build DeepIceDrain

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build DeepIceDrain App
      run: docker build --file Dockerfile --tag weiji14/deepicedrain --target app .
