name: Test DeepIceDrain package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.os }} - Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        python_version: [3.8]
        os: [ubuntu-latest]

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Setup Miniconda and install conda dependencies
        uses: goanpeca/setup-miniconda@v1.4.1
        with:
          miniconda-version: py38_4.8.2
          environment-file: environment.yml
          activate-environment: deepicedrain
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          show-channel-urls: true
          auto-activate-base: false

      - name: Install Poetry python dependencies
        shell: bash -l {0}
        run: poetry install

      - name: Display virtualenv and installed package information
        shell: bash -l {0}
        run: |
          conda info
          conda list
          poetry env info
          poetry show

      - name: Code Quality
        shell: bash -l {0}
        run: poetry run black . --check

      - name: Test with pytest
        shell: bash -l {0}
        run: poetry run pytest --verbose tests/
